{{- if .Values.hpa.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.hpa.labels .Values.common.labels ) "context" . ) }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.hpa.annotations .Values.common.annotations ) "context" . ) }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if .Values.common.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "common.names.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- if gt (int .Values.hpa.targetCPU) 0 }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPU }}
    {{- end }}
    {{- if gt (int .Values.hpa.targetMemory) 0 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemory }}
    {{- end }}
  {{- if .Values.hpa.behavior }}
  behavior: {{- toYaml .Values.hpa.behavior | nindent 4 }}
  {{- end }}
{{- end }}
