{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.pvc.labels .Values.common.labels ) "context" . ) }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.pvc.annotations .Values.common.annotations ) "context" . ) }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if .Values.common.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  {{- end }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}
