{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.rbac.role.labels .Values.common.labels ) "context" . ) }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.rbac.role.annotations .Values.common.annotations ) "context" . ) }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if .Values.common.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- if .Values.rbac.role.rules }}
rules: {{- toYaml .Values.rbac.role.rules | nindent 2 }}
{{- end }}
{{- end }}
