{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.secret.labels .Values.common.labels ) "context" . ) }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.secret.annotations .Values.common.annotations ) "context" . ) }}
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
  {{- if .Values.common.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
{{- if .Values.secret.data }}
data: {{- include "common.tplvalues.render" ( dict "value" .Values.secret.data "context" $ ) | nindent 2 }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData: {{- include "common.tplvalues.render" ( dict "value" .Values.secret.stringData "context" $ ) | nindent 2 }}
{{- end }}
{{- end }}
